# Generated by Django 4.2.3 on 2023-07-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_servicerecord_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(verbose_name='service date'),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='main_app.feature'),
        ),
    ]
